/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kahvesiparis;

/**
 *
 * @author BIP
 */
public class kahve extends javax.swing.JFrame {

    /**
     * Creates new form radioButton
     */
    public kahve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        radAzSeker = new javax.swing.JRadioButton();
        radOrtaSeker = new javax.swing.JRadioButton();
        radCokSeker = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblHesap = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSiparisVer = new javax.swing.JButton();
        radKucukBoy = new javax.swing.JRadioButton();
        radOrtaBoy = new javax.swing.JRadioButton();
        radBuyukBoy = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup2.add(radAzSeker);
        radAzSeker.setText("Az");

        buttonGroup2.add(radOrtaSeker);
        radOrtaSeker.setText("Orta");

        buttonGroup2.add(radCokSeker);
        radCokSeker.setText("Çok");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kahvenizi nasıl alırsınız?");

        lblHesap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHesap.setText("Hesap:");

        jLabel2.setText("Boy:");

        btnSiparisVer.setText("Sipariş Ver");
        btnSiparisVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiparisVerActionPerformed(evt);
            }
        });

        buttonGroup1.add(radKucukBoy);
        radKucukBoy.setText("Küçük");
        radKucukBoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radKucukBoyActionPerformed(evt);
            }
        });

        buttonGroup1.add(radOrtaBoy);
        radOrtaBoy.setText("Orta");

        buttonGroup1.add(radBuyukBoy);
        radBuyukBoy.setText("Büyük");

        jLabel3.setText("Şeker");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radAzSeker)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radOrtaSeker)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radCokSeker))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radBuyukBoy)
                                .addGap(22, 22, 22)
                                .addComponent(radOrtaBoy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radKucukBoy))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHesap)
                        .addGap(60, 60, 60)
                        .addComponent(btnSiparisVer)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radOrtaBoy)
                    .addComponent(radBuyukBoy)
                    .addComponent(radKucukBoy))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radAzSeker)
                    .addComponent(radOrtaSeker)
                    .addComponent(radCokSeker))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiparisVer)
                    .addComponent(lblHesap))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiparisVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiparisVerActionPerformed
        int hesap = 5;
        if(radBuyukBoy.isSelected()){
            hesap = hesap +5;
        }
        if(radOrtaBoy.isSelected()){
            hesap = hesap +3;
        }
        if(radAzSeker.isSelected()){
            hesap = hesap +1;
        }
        if(radOrtaSeker.isSelected()){
            hesap = hesap +2;
        }
        if(radCokSeker.isSelected()){
            hesap = hesap +3;
        }
        lblHesap.setText("Hesap :"+hesap+"TL");
    }//GEN-LAST:event_btnSiparisVerActionPerformed

    private void radKucukBoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radKucukBoyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radKucukBoyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kahve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kahve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kahve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kahve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kahve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiparisVer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblHesap;
    private javax.swing.JRadioButton radAzSeker;
    private javax.swing.JRadioButton radBuyukBoy;
    private javax.swing.JRadioButton radCokSeker;
    private javax.swing.JRadioButton radKucukBoy;
    private javax.swing.JRadioButton radOrtaBoy;
    private javax.swing.JRadioButton radOrtaSeker;
    // End of variables declaration//GEN-END:variables
}
